spring:
  # 应用
  application:
    name: tliasmanagement
  #  mybatis数据库连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/user
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  servlet:
    #配置单个文件最大上传大小
    multipart.max-file-size: 10MB
    # 配置单个请求最大上传大小(一次请求可以上传多个文件)
    multipart.max-request-size: 100MB

# 日志
mybatis:
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 开启驼峰命名的映射
  configuration.map-underscore-to-camel-case: true

#spring事务管理日志
logging:
  level.org.springframework.jdbc.support.JdbcTransactionManager: debug
  
  # 阿里云对象存储配置
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: tlias-jinan67



